import type { SemanticType } from '../models/semantic'

export const SEMANTIC_TYPES: Record<string, SemanticType> = {
  EMPTY: {
    id: 'EMPTY',
    name: 'Empty',
    code: 0,
    category: 'EMPTY',
    edgeWeight: 0,
    priority: 0,
    allowsDoor: false,
  },
  WALL: {
    id: 'WALL',
    name: 'Wall',
    code: 1,
    category: 'INFRASTRUCTURE',
    edgeWeight: 70,
    priority: 70,
    allowsDoor: true,
    defaultWidth: 0.2,
    defaultHeight: 4,
    fill: '#4b5563',
    stroke: '#1f2937',
  },
  DESK: {
    id: 'DESK',
    name: 'Desk',
    code: 2,
    category: 'FURNITURE',
    edgeWeight: 20,
    priority: 30,
    allowsDoor: false,
    defaultWidth: 1.4,
    defaultHeight: 0.7,
    fill: '#c4a574',
    stroke: '#8b6914',
  },
  CHAIR: {
    id: 'CHAIR',
    name: 'Chair',
    code: 3,
    category: 'FURNITURE',
    edgeWeight: 10,
    priority: 20,
    allowsDoor: false,
    defaultWidth: 0.5,
    defaultHeight: 0.5,
    fill: '#60a5fa',
    stroke: '#1d4ed8',
  },
  TABLE: {
    id: 'TABLE',
    name: 'Table',
    code: 4,
    category: 'FURNITURE',
    edgeWeight: 20,
    priority: 30,
    allowsDoor: false,
    defaultWidth: 1.6,
    defaultHeight: 0.8,
    fill: '#d6b88a',
    stroke: '#92400e',
  },
  MEETING_ROOM: {
    id: 'MEETING_ROOM',
    name: 'Meeting Room',
    code: 5,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 6,
    defaultHeight: 5,
    fill: 'rgba(59, 130, 246, 0.2)',
    stroke: '#2563eb',
  },
  CABIN: {
    id: 'CABIN',
    name: 'Cabin',
    code: 6,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 4,
    defaultHeight: 3.5,
    fill: 'rgba(16, 185, 129, 0.2)',
    stroke: '#059669',
  },
  CONFERENCE_ROOM: {
    id: 'CONFERENCE_ROOM',
    name: 'Conference Room',
    code: 7,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 8,
    defaultHeight: 6,
    fill: 'rgba(99, 102, 241, 0.2)',
    stroke: '#4f46e5',
  },
  OPEN_WORKSPACE: {
    id: 'OPEN_WORKSPACE',
    name: 'Open Workspace',
    code: 8,
    category: 'ROOM',
    edgeWeight: 8,
    priority: 75,
    allowsDoor: true,
    defaultWidth: 12,
    defaultHeight: 10,
    fill: 'rgba(148, 163, 184, 0.15)',
    stroke: '#64748b',
  },
  DOOR: {
    id: 'DOOR',
    name: 'Door',
    code: 9,
    category: 'INFRASTRUCTURE',
    edgeWeight: 0,
    priority: 100,
    allowsDoor: false,
    defaultWidth: 0.9,
    defaultHeight: 0.15,
    fill: '#f59e0b',
    stroke: '#b45309',
  },
  SOFA: {
    id: 'SOFA',
    name: 'Sofa',
    code: 10,
    category: 'FURNITURE',
    edgeWeight: 15,
    priority: 25,
    allowsDoor: false,
    defaultWidth: 2,
    defaultHeight: 0.9,
    fill: '#a78bfa',
    stroke: '#6d28d9',
  },
  PLANT: {
    id: 'PLANT',
    name: 'Plant',
    code: 11,
    category: 'DECORATION',
    edgeWeight: 5,
    priority: 10,
    allowsDoor: false,
    defaultWidth: 0.4,
    defaultHeight: 0.4,
    fill: '#86efac',
    stroke: '#15803d',
  },
  WINDOW: {
    id: 'WINDOW',
    name: 'Window',
    code: 12,
    category: 'INFRASTRUCTURE',
    edgeWeight: 40,
    priority: 60,
    allowsDoor: false,
    defaultWidth: 1.2,
    defaultHeight: 0.15,
    fill: '#7dd3fc',
    stroke: '#0369a1',
  },
  STAIRS: {
    id: 'STAIRS',
    name: 'Stairs',
    code: 13,
    category: 'INFRASTRUCTURE',
    edgeWeight: 50,
    priority: 65,
    allowsDoor: false,
    defaultWidth: 2,
    defaultHeight: 3,
    fill: '#fdba74',
    stroke: '#c2410c',
  },
  KITCHEN: {
    id: 'KITCHEN',
    name: 'Kitchen',
    code: 14,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 5,
    defaultHeight: 4,
    fill: 'rgba(251, 146, 60, 0.2)',
    stroke: '#ea580c',
  },
  RECEPTION: {
    id: 'RECEPTION',
    name: 'Reception',
    code: 15,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 6,
    defaultHeight: 4,
    fill: 'rgba(244, 114, 182, 0.2)',
    stroke: '#db2777',
  },
  STORAGE: {
    id: 'STORAGE',
    name: 'Storage',
    code: 16,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 3,
    defaultHeight: 2.5,
    fill: 'rgba(156, 163, 175, 0.25)',
    stroke: '#4b5563',
  },
  RESTROOM: {
    id: 'RESTROOM',
    name: 'Restroom',
    code: 17,
    category: 'ROOM',
    edgeWeight: 10,
    priority: 80,
    allowsDoor: true,
    defaultWidth: 3,
    defaultHeight: 2.5,
    fill: 'rgba(34, 211, 238, 0.2)',
    stroke: '#0891b2',
  },
  PILLAR: {
    id: 'PILLAR',
    name: 'Pillar',
    code: 18,
    category: 'INFRASTRUCTURE',
    edgeWeight: 60,
    priority: 85,
    allowsDoor: false,
    defaultWidth: 0.6,
    defaultHeight: 0.6,
    fill: '#9ca3af',
    stroke: '#4b5563',
  },
  UNUSABLE_SPACE: {
    id: 'UNUSABLE_SPACE',
    name: 'Unusable Space',
    code: 19,
    category: 'INFRASTRUCTURE',
    edgeWeight: 50,
    priority: 90,
    allowsDoor: false,
    defaultWidth: 3,
    defaultHeight: 2,
    fill: '#d1d5db',
    stroke: '#6b7280',
  },
}

export function getSemanticType(typeId: string): SemanticType {
  const type = SEMANTIC_TYPES[typeId]
  if (!type) {
    throw new Error(`Unknown semantic type: ${typeId}`)
  }
  return type
}

export function listSemanticTypes(): SemanticType[] {
  return Object.values(SEMANTIC_TYPES)
}

export function getSemanticCode(typeId: string): number {
  return getSemanticType(typeId).code
}

export function getEdgeWeight(typeId: string): number {
  return getSemanticType(typeId).edgeWeight
}

export function getPriority(typeId: string): number {
  return getSemanticType(typeId).priority
}
